### ISSUE TITLE
Please provide directLink like knx adapter

### ISSUE THREAD

**Issue by TA2k** [iobroker-community-adapters/ioBroker.openknx#100]

**Comment by boellner** [comment]
Please provide the requirements, a description what "directLink" is and why we should add it to the KNX communication adapter.

**Comment by TA2k** [comment]
https://github.com/ioBroker/ioBroker.knx#direct-link-non-knx-state-to-knx-vice-verse

**Comment by boellner** [comment]
This is not answering the question, why and how should introduce this in this adapter?

**Comment by TA2k** [comment]
to link a non KNX ioBroker state directly to a GA.
Like in knx adapter

**Comment by boellner** [comment]
the openknx adapter is here to handle knx signals, alias on top exist to combine signals form different systems. Im not planning to weaken this simple layered architecture for no real good reason

**Comment by TA2k** [comment]
This ok but maybe an other contributor will add this feature. 
To integrate non knx device to the knx bus.

**Comment by boellner** [comment]
please refrain from reopening tickets without adding value to the discussion

**Comment by TA2k** [comment]
I make two additional points.
It make sense like in the KNX adapter to allow iobroker states in to the knx bus
I dont see the point why its weaken the architecture of the adapter. 
I dont see a real architecture its only consuming a library

**Comment by boellner** [comment]
Them please provide arguments to do it any other way, complaining doesnt help.
I havent seen any real argument why it is needed to mix pure knx signals with data from other sources .
Combining signals is perfectly done a layer above the knx adapter. Because of this was done somewehere else isn't an argument. 
There is a good solution for the problem, use it.

**Comment by TA2k** [comment]
I don't see a good solution please provide a good explanation how this problem is solved with alias before closing feature requests

**Comment by TA2k** [comment]
Why you closing this discussion? Please provide details about your proposed solution.

**Comment by boellner** [comment]
Now it is getting rediculous, i have explained you the architecture of the adapter many times and you continue to request over and over the same things without explaining the need or why the existing solution is not useful.

**Comment by TA2k** [comment]
I explained the reason for the request your answer is the feature is not need because it possible via alias. 
Can you please elaborate how can I simulate this functionality via alias and add this to the readme?

**Comment by boellner** [comment]
Since Adapter Version 2.0.6 it is possible to link a non KNX ioBroker state directly to a GA.
Set this up in the alias object, and use the alais object and subsequent logic.

    "alias": {
      "id": {
        "read": "nonknx",
        "write": "openknx.0..."
      }

**Comment by TA2k** [comment]
Ok this is not replacing the functionality but anyway the feature is not allowed.
If a user wants it he has to fork the adapter.
Thanks for the discussion.

**Comment by boellner** [comment]
what is the funcionality then ? unfortunately im not able to understand what you really want to achieve; what is not working without the change ?

**Comment by TA2k** [comment]
A alias has a state to receive values and a state to write values in.
A directlink is mirroring a complete non knx state into the knx bus with all knx capabilites
But the request is declined and closed please respect this.

**Comment by boellner** [comment]
that is a description of the concepts, it is still not clear what you want to change and for what it is needed
but agreed , lets end this for once and all

**Comment by tillsteinbach** [comment]
Maybe I did not understand the concept of the Alias. My usecase is:
I have a heater integrated with modbus in iobroker and want to directly copy the values coming from the heater to a knx group address.
Other example: I have values coming from knx and I want those to be copied to a mqtt backed state. how do I realize that with the aliases?

**Comment by tillsteinbach** [comment]
Well, it got feedback…
Creating scripts just to copy values from A to B? That does not seem like the most elegant solution…

**Comment by Apollon77** [comment]
Yes got feedback by (a very lowwww) chance. these scripts are one liners per State

**Comment by tillsteinbach** [comment]
Huh, one liners?
