### ISSUE TITLE
Adapter does not generate ACK

### ISSUE THREAD

**Issue by cdaerr** [iobroker-community-adapters/ioBroker.openknx#133]
**Describe the bug**  
Set a Value to an Datapoint without ACK in ioBroker does leave the value not acknowledged. If the value ist read on the KNX Bus the value is acknowledged in ioBroker Datapoint.

**To Reproduce**  
1. Set a value in the Object pane. Value is send to Bus
2. No ACK is stored in Datapoint
3. Send the Value on KNX Bus (e.g. by ETS) the value is read by openKNX and the ack is set.

**Expected behavior**  
ACK is set when openKNX sends tha value successful on the bus.

**Screenshots & Logfiles**  
![grafik](https://user-images.githubusercontent.com/98185044/153775835-6ce06a2f-a55d-4ca5-a314-b7efe5517ea8.png)

**Versions:**  
 - Adapter version: 0.1.18
 - JS-Controller version: 3.3.22
 - Node version: v14.19.0
 - Operating system: ubuntu 20.04

**Comment by boellner** [comment]
Thank you for the precise description of the issue. 2 questions:
-What is the consequence of this behavior, what is not working for you if it is not changed? Basically, why do you want it changed?
-Can you point me to the requirement from where you derieve your expectation?


this is what I have written in the documentation:
[](https://github.com/iobroker-community-adapters/ioBroker.openknx#ack-flags)ACK flags
Applications shall not set ack flags, application is notified from this adapter by the ack flag if data is updated. KNX Stack sets the ack flag of the linked IoBroker object on receiption of a group address. Sent frames on KNX do not result into a ack of the writing object.
---
https://github.com/ioBroker/ioBroker/wiki/Adapter-Development-Documentation
"Status" has "ack" flag as true and indicate that it is from device or service. E.g. if the weather adapter got new weather forecast, it will be published with ack=true or if homematic thermometer measures new temperature, it will be published with ack=true too. Even if the user physically will switch the light on, the new state will be published with ack=true.

Sending on the bus alone does not neccesarily mean it is accepted and executed by the device or service. There is very often no clear device behind it. 
This concept makes imo not much sense. The alias mechanism has a way to combine sender and receiver.

**Comment by Apollon77** [comment]
When I understand correctly then the user want to "see" an acknowledgement that the value he is setting with "ack=false" was successfully sent and processed. This is irrelevant when the value from device is returned on the same object. But when you have one object to set values and the real value is on a second state then the "set state" will always be ack=false ...

Formally this is "Out of specifications" regarding ioBroker and so it is a convenient topic ... Some users like when "values are green in admin" (green===ack=true) :-) I understand it that way at least

**Comment by DutchmanNL** [comment]
agree with @Apollon77, honestly its a little difficult when different states (like hier in KNX like command & status) are used.
The ACK flag perfectly indicates if the required change has been applied.

Practise-Example: I use this very common for HomeMatic and Zigbee. A kind of watchdog script subscribes on al states I write values to and checks like 1 or 2 second later if the ACK is set true or false.

For system like alarm this is very important for my automation as I need to ensure 100% the value I did set is really propagated to the system and if not I need to act (like monitoring alarm or resending the value)

**Comment by cdaerr** [comment]
Hello Mr. Böllner,

thanks for your answer. I have read your documentation, but in my understanding a missing ACK says there went something wrong.

My understanding of ACK-Flag is this:
https://haus-automatisierung.com/software/iobroker/2021/02/02/iobroker-steuere-aktualisiere-bestaetigt.html
![grafik](https://user-images.githubusercontent.com/98185044/154845972-d74c7ea0-db3c-4a8e-a654-4ccb17c02070.png)

The chapter of "Adapter Development Documentation" you quoted, describes a datapoint were command and status response are the same datapoint. But for KNX this is not the case, unless I use an Alias with different read and write. In the example above commands are send to "Licht_14_Essen_Decke_Wert" and the response is send to "Licht_14_Essen_Decke_Wert_Status". So I am not sure, that this example is applicable for KNX connections.

**Comment by Apollon77** [comment]
Correct, In fact the sentence need to be

"Hat alles geklappt sendet das Gerät üblicherweise nach Ausführen der Aktion den dann aktualisierten Wert zurück und damit wird ein neuer Wert vom Adapter bestätigt."

Formal kann ein gerät alles tun basierend auf einem Kommando - ich würde nie behaupten das der Wert danach immer der gesetzte sein muss. Und es gibt auch keine Formale garantie das das gerät den State mit dem neuen Wert bestätigt der geschrieben wurde. Da gibts genügend gegenbeispiele.

**Comment by DutchmanNL** [comment]
> Adapter die in so einem Fall trotzdem den Wert bestätigten tun Sie das weil sie das aus convenience Grnden für die User tun. Entscheidung des Devs

aggree, with the addition that the ACK flack can be very useful (as explained before) but indeed also the argument of Apollon should be considered. ACK does not mean the value is really set as wished ( I did send 1, the value return is 6 with ACK true) it basically only says the value is confirmed by a trusted source.

I am a little bit struggling in the structure of KNX as we have the Set and Value state (if I understand correctly)
What I try to say here, normally these states (in most regular adapters)) are combined so the state to set the value is equal to the state receiving the value and the ACCK flack then show ah it did come from the source

**Comment by boellner** [comment]
@cdaerr I need to know your use case:
you send Licht_14_Essen_Decke_Wert and get the Licht_14_Essen_Decke_Wert_Status with ack. Why do you need to eval. the sending value:

these were my design decisions
-I dont think that sending on the bus is technically checking for the LDataInd flag. It is not guaranteed that the meant receiving device has got the data. If you need certainity, you have to build in a dedicated mechanism.
-same group address/iob object CAN be configured for sending and receiving data. generate ack flags on sending, then you cannot differenciate.
-you can trigger different knx send commands by writing onto the iob object. Sending via knx command GroupValue_read will result on GroupValue_write. Here you dont want 2 ack triggers with different object values.

**Comment by cdaerr** [comment]
Not all KNX Group Adresses have an corresponding status Groupadress. If there is one you can make an alias and you get the expected behavior. If there is no Status response from an KNX actuator you don't know anything.

Sending and receiving in one Group adress is not the normal KNX implementation but sometimes it is necessary. Then you would get two ACK. Does this cause problems?

The answer of an GroupValue_read is an GroupValue_response:
![grafik](https://user-images.githubusercontent.com/98185044/155891886-b1e61343-2be8-4fd4-921d-5dc06fcfda6c.png)

KNX devices mostly ignore this GroupValue_response, beside that the A-Flag of KO is set.
I don't see where the 2 ack shall come from and what is the problem on it.

I think I actually do not understand the sense of the ACK mechanism of ioBroker. For beginners the control and update mechnism is very confusing, especially when every adapter handles it in his own way. There should be an consistant way of handling ACK in different adapters. At the moment it only causes trouble when triggering on objects (not especially openKNX).

**Comment by boellner** [comment]
I make it a configurable option, 0.1.23 @cdaerr please test

**Comment by cdaerr** [comment]
Thanks,

I updated and tested today. And I had some strange behavoir:

I changed a dataoint (Licht_26_Diele_OG_Decke_Ext_Taster_Kurz) to true by using the Admin interface (only command of course):
![ACK_openKNX](https://user-images.githubusercontent.com/98185044/159161147-e6c994fe-df15-411d-934b-1f3f2d82dbc4.jpg)

I immediatlely got an ACK true. The timestamp of command and update are identic, there is no delay. And the origin of the update (ACK true) is also the admin adapter I would have expected, that the update has origin openKNX adapter.

The ACK is also generated, when the KNX interface is not reachable. Network connection faild. I would have expected, that there will be no ACK, when the adapter couldn't send the command to KNX bux.

Here is an example of same test with TR-064 Adapter. I sended false from admin Adapter and got a false with ACK true from TR-064:
![ACK_TR064](https://user-images.githubusercontent.com/98185044/159161497-17836ffc-824c-4b9b-870e-f750ae5c72c1.jpg)

**Comment by boellner** [comment]
In upcoming version 0.1.25 behavior is chaning and timestamp etc. is not copied over from receiving object.
I cannot control when and how the ack gets generated. It is coming from a callback from the library, and it does not check for any confirmance on the bus.

**Comment by cdaerr** [comment]
I don't think that the ACK makes sense, when it is send every time, regardless wheter the command was send or not.

**Comment by boellner** [comment]
inplemented in v0.2.2
