### ISSUE TITLE
Error in log on KNX GroupValueRead

### ISSUE THREAD

**Issue by cdaerr** [iobroker-community-adapters/ioBroker.openknx#159]
An GroupValueRead on KNX causes an error in ioBroker Log:
![grafik](https://user-images.githubusercontent.com/98185044/159174954-06f89385-9c2e-4660-ad3d-d1e97e64ac07.png)

The corresponding ETS data looks well for me:
![grafik](https://user-images.githubusercontent.com/98185044/159174970-999fa138-ec72-41f3-9485-2971d74015e0.png)

Here a detailed view on the last GroupValueRead (#1964):
![grafik](https://user-images.githubusercontent.com/98185044/159175085-fa3cad9d-80f6-4f38-a1e9-f59319985ef5.png)

So what is the problem with this communication data?

Adapter Version: 0.1.23

**Comment by cdaerr** [comment]
After downgrade to 0.1.22 the errors disappier.

**Comment by boellner** [comment]
display problem, fixed in  0.1.24 please check

**Comment by cdaerr** [comment]
I get errors, when openKNX is answering to the GroupValueRead:

![grafik](https://user-images.githubusercontent.com/98185044/161371484-2c244077-be9e-4134-93e6-e7cd3ba5c3a8.png)
