### ISSUE TITLE
openknx import of group addresses via xml file

### ISSUE THREAD

**Issue by knutknutso** [iobroker-community-adapters/ioBroker.openknx#168]
Dear Users

**Describe the bug**  
"SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data"

I try to import via the adapter the GA from the ETS export file, described as in readme.
ETS Version 5.7.4 (Build 1093)

I tried in 2 steps, all of them provoked above mentioned failure description

First trial.
Group Adress export via ETS Group Export as shown in picture
![grafik](https://user-images.githubusercontent.com/102857583/161379901-5c96e754-9d38-4e03-a35a-7a5948a6f030.png)

Error-Result "SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data"

Second trial.
Extract the knxproj-Projekt-File with 7zip to "knx_master.xml"
The same procedure to import the file with the adapter, same failure as above

**Versions:**  
 - Adapter version: 0.1.22
 - JS-Controller version: 4.0.21
 - Node version: v12.22.11
 - Operating system: Debian bullseye

Thank you for your help

**Comment by boellner** [comment]
what xml format did you use?
Please provide me the file or a stripped down version of it to reproduce the issue here
