### ISSUE TITLE
Not importing actually used GAs with info: The GA is not connected to a KO in ETS

### ISSUE THREAD

**Issue by CC1337** [iobroker-community-adapters/ioBroker.openknx#169]
Hi,

I am missing actually used GAs in ioBroker, in particular some feedback and also write GAs for a older Gira dimmer "2174 00" https://partner.gira.de/data3/21713410.pdf

I exported the GAs like this:
![grafik](https://user-images.githubusercontent.com/4866744/161424102-aeba6f5c-d22b-46aa-ab33-4d89d1e72978.png)

Excerpt:

```
<GroupRange Name="Licht" RangeStart="45312" RangeEnd="45567">
      <GroupAddress Name="L_D02_01 Licht Flur Wand SCHALTEN" Address="22/1/0" DPTs="DPST-1-1" />
      <GroupAddress Name="L_D02_02 Licht Diele Wand SCHALTEN" Address="22/1/1" DPTs="DPST-1-1" />
      <GroupAddress Name="LD_D02_01 Licht Flur/Diele Decke Spots SCHALTEN" Address="22/1/2" DPTs="DPT-1" />
      <GroupAddress Name="LD_D02_01 Licht Flur/Diele Decke Spots DIMMEN" Address="22/1/3" DPTs="DPT-3" />
      <GroupAddress Name="LD_D02_01 Licht Flur/Diele Decke Spots HELLIGKEIT" Address="22/1/4" />
      <GroupAddress Name="L_D02 Flur/Diele Wand SCHALTEN" Address="22/1/49" DPTs="DPT-1" />
      <GroupAddress Name="L_D02 Flur/Diele alles SCHALTEN" Address="22/1/50" DPTs="DPST-1-1" />
</GroupRange>
<GroupRange Name="Licht RM" RangeStart="45568" RangeEnd="45823">
      <GroupAddress Name="L_D02_01 Licht Flur Wand SCHALTEN RM" Address="22/2/0" DPTs="DPST-1-1" />
      <GroupAddress Name="L_D02_02 Licht Diele Wand SCHALTEN RM" Address="22/2/1" />
      <GroupAddress Name="LD_D02_01 Licht Flur/Diele Decke Spots SCHALTEN RM" Address="22/2/2" DPTs="DPST-1-1" />
      <GroupAddress Name="LD_D02_01 Licht Flur/Diele Decke Spots HELLIGKEIT RM" Address="22/2/4" />
      <GroupAddress Name="LD_D02_01 Licht Flur/Diele Decke Spots BETRIEBSSTUNDEN RM" Address="22/2/5" />
</GroupRange>
```

Assigned them and wrote the application before of course:
![grafik](https://user-images.githubusercontent.com/4866744/161424134-d9dbef0c-2e2f-4ed2-ae01-c66fcd68b8c9.png)

Note: The 2 marked ones are 2 of the missing ones and they are NOT used by other actuators in ETS, they are supposed to be used via ioBroker.

![grafik](https://user-images.githubusercontent.com/4866744/161424185-eee7c33d-4ce8-4ce7-83f1-9cd20195552e.png)

The unused scene might be correct but I am wondering about the others.
Here is what I would like to see:
![grafik](https://user-images.githubusercontent.com/4866744/161424221-83844fa2-15f4-40d7-83ed-efe8aacb5d85.png)

and what I actually see:
![grafik](https://user-images.githubusercontent.com/4866744/161424252-e6f1f498-3285-4843-82da-9d82ecaf89bf.png)

Any idea what I should try next, or any additional info needed?
Please note: As I see the difference already in the XML, it is unlikely an issue with the adapter but my config/ETS/how I export. Any help would still be very appreciated :)

I am using ETS 6.0.3

**Comment by boellner** [comment]
we dont know what DPT is behind
<GroupAddress Name="LD_D02_01 Licht Flur/Diele Decke Spots HELLIGKEIT" Address="22/1/4" />
Go to your ETS GA listing, and set there a matching DPT.
