### ISSUE TITLE
remove extendObject

### ISSUE THREAD

**Issue by boellner** [iobroker-community-adapters/ioBroker.openknx#17]
I make an example.

not onlyAddNewObjects - setObject

"common": {
"added_field": "value",
"type": "boolean_overwritten",

results in:
"common": {
"type": "boolean",

'This is the intended behavior. Object should be genereated new, removing no longer defined fields. Its a clean install without having to erase objet tree by hand or reinstall the adapter.
Dont care about history adapter settings here, if lost this is toleratable, because user would use onlyAddNewObjects to ensure its preserved.

onlyAddNewObjects - extendObject

"common": {
"added_field": "value",
"type": "boolean_overwritten",

results in:
"common": {
"added_field": "value",
"type": "boolean",

Unintended behavior, I should keep "boolean_overwritten" .
As you said ExtendObject will override all data that are in the structure and so updates the objects.
Is there a way to control this behavoir?
If not I will go back to setObjectNotExists (see commented out in code), with the small disadvantage that it will not add newly defined fields.

**Comment by boellner** [comment]
merged

**Comment by Apollon77** [comment]
> As you said ExtendObject will override all data that are in the structure and so updates the objects.
Is there a way to control this behavoir?

No, normally Adapters "own" the objects and usrs should never touch the objects. The only "part" which is allowed to be adjusted by users is the common.cstom part where adapzers can offer custom UIs dio add data to it.

So it is a special case that you allow users to modify objects
