### ISSUE TITLE
I get errors, when openKNX is answering to the GroupValueRead:

### ISSUE THREAD

**Issue by cdaerr** [iobroker-community-adapters/ioBroker.openknx#183]
I get errors, when openKNX is answering to the GroupValueRead:

![grafik](https://user-images.githubusercontent.com/98185044/161371484-2c244077-be9e-4134-93e6-e7cd3ba5c3a8.png)

_Originally posted by @cdaerr in https://github.com/iobroker-community-adapters/ioBroker.openknx/issues/159#issuecomment-1086570613_

Adapter Version: v0.1.25

**Comment by boellner** [comment]
fixed in 0.1.26

**Comment by cdaerr** [comment]
Can't find Version 0.1.26.
latest Version is 0.1.25:
![grafik](https://user-images.githubusercontent.com/98185044/164967586-13c3736d-471d-48c1-a217-ccc33c509d51.png)
