### ISSUE TITLE
Remove iobroker.js-controller as dev dependency!!

### ISSUE THREAD

**Issue by Apollon77** [iobroker-community-adapters/ioBroker.openknx#185]
see https://github.com/iobroker-community-adapters/ioBroker.openknx/pull/184#event-6459628062

**Comment by boellner** [comment]
It is needed for unit testing

**Comment by Apollon77** [comment]
Then you do something wrong ... the testing installs normally what it needs himself, no other adapter needs it ... so why you?

**Comment by boellner** [comment]
not clear to me, here is the log:
https://github.com/iobroker-community-adapters/ioBroker.openknx/runs/6134002409?check_suite_focus=true
> Cannot find js-controller

**Comment by Apollon77** [comment]
Do you have unit tests? I think not. please comment https://github.com/iobroker-community-adapters/ioBroker.openknx/blob/master/.github/workflows/test-and-release.yml#L47-L48 ... the integration tests are run in the next step of the github actions

**Comment by AlCalzone** [comment]
https://github.com/iobroker-community-adapters/ioBroker.openknx/blob/7e7476a2c0ad2e1e8586d7ae48b85667ff5b04c4/package.json#L72 seems to execute the integration test script I think. We might have forgotten to update that line when renaming the predefined test scripts. I'd change this line to
```
"test:js": "mocha --config test/mocharc.custom.json \"lib/**/*.test.js\"",
```
so it doesn't look at the extra files in the test folder

**Comment by AlCalzone** [comment]
Ok I found the issue. You have the file `main.test.js` which requires `main.js`:
https://github.com/iobroker-community-adapters/ioBroker.openknx/blob/3c44d0a5e40f61cefee54c754b0915593456bc55/main.test.js#L13

you cannot just do this from outside a proper ioBroker setup.

**Comment by Apollon77** [comment]
@boellner Please remove js-controller as a dependency!
