### ISSUE TITLE
Regular disconnects with MDT IP-Interface behind WLAN bridge

### ISSUE THREAD

**Issue by savek-cc** [iobroker-community-adapters/ioBroker.openknx#255]
The OpenKNX-Adapter regularly disconnects from the MDT IP-Gateway every few minutes.
It apparently always starts with a "Received DISCONNECT_REQUEST message" - but I can't figure out why this is happening.
Due to the regular disconnects, the adapter is somewhat unusable because it misses most of the status updates on the KNX bus.
ETS and the other KNX adapter do not experience this behavior. Any ideas are very much welcome.

Adapter Version 2.0.6
iobroker -v: 4.0.21

Log:
openknx.0 | 2022-08-16 11:41:28.937 | info | Connected!
-- | -- | -- | --
openknx.0 | 2022-08-16 11:41:28.937 | silly | [debug] 2022-08-16 09:41:28.937 (idle): zzzz...
openknx.0 | 2022-08-16 11:41:28.937 | silly | [debug] 2022-08-16 09:41:28.937 --- Connected in TUNNELING mode ---
openknx.0 | 2022-08-16 11:41:28.937 | silly | [debug] 2022-08-16 09:41:28.937 Got connection state response, connstate: NO_ERROR, channel ID: 16
openknx.0 | 2022-08-16 11:41:28.937 | silly | [trace] 2022-08-16 09:41:28.936 (connecting): Received CONNECTIONSTATE_RESPONSE message: {"header_length":6,"protocol_version":16,"service_type":520,"total_length":8,"connstate":{"channel_id":16,"status":0}}
openknx.0 | 2022-08-16 11:41:28.936 | silly | [debug] 2022-08-16 09:41:28.936 Inbound message: 0610020800081000
openknx.0 | 2022-08-16 11:41:28.935 | silly | States user redis pmessage openknx.0.*/openknx.0.info.connection:{"val":false,"ack":true,"ts":1660642888934,"q":0,"from":"system.adapter.openknx.0","user":"system.user.admin","lc":1660642888934}
openknx.0 | 2022-08-16 11:41:28.932 | silly | [trace] 2022-08-16 09:41:28.932 (connecting): UDP sent OK: CONNECTIONSTATE_REQUEST 06100207001010000801000000000000
openknx.0 | 2022-08-16 11:41:28.932 | silly | [trace] 2022-08-16 09:41:28.932 (connecting): Sending CONNECTIONSTATE_REQUEST ==> {"header_length":6,"protocol_version":16,"service_type":519,"total_length":16,"hpai":{"protocol_type":1,"tunnel_endpoint":"0.0.0.0:0"},"connstate":{"channel_id":16,"state":0}}
openknx.0 | 2022-08-16 11:41:28.932 | silly | [debug] 2022-08-16 09:41:28.932 got connect response
openknx.0 | 2022-08-16 11:41:28.932 | silly | [trace] 2022-08-16 09:41:28.932 (connecting): Received CONNECT_RESPONSE message: {"header_length":6,"protocol_version":16,"service_type":518,"total_length":20,"connstate":{"channel_id":16,"status":0},"hpai":{"header_length":8,"protocol_type":1,"tunnel_endpoint":"0.0.0.0:0"},"cri":{"header_length":4,"connection_type":4,"knx_layer":17,"unused":200}}
openknx.0 | 2022-08-16 11:41:28.932 | silly | [debug] 2022-08-16 09:41:28.932 Inbound message: 06100206001410000801000000000000040411c8
openknx.0 | 2022-08-16 11:41:28.927 | silly | [trace] 2022-08-16 09:41:28.927 (connecting): UDP sent OK: CONNECT_REQUEST 06100205001a0801000000000000080100000000000004040200
openknx.0 | 2022-08-16 11:41:28.926 | silly | [trace] 2022-08-16 09:41:28.926 (connecting): Sending CONNECT_REQUEST ==> {"header_length":6,"protocol_version":16,"service_type":517,"total_length":26,"hpai":{"protocol_type":1,"tunnel_endpoint":"0.0.0.0:0"},"tunn":{"protocol_type":1,"tunnel_endpoint":"0.0.0.0:0"},"cri":{"connection_type":4,"knx_layer":2,"unused":0},"connstate":{"state":0}}
openknx.0 | 2022-08-16 11:41:28.926 | silly | [debug] 2022-08-16 09:41:28.926 Connecting via 192.168.200.25...
openknx.0 | 2022-08-16 11:41:28.926 | silly | [debug] 2022-08-16 09:41:28.926 useTunneling=true
openknx.0 | 2022-08-16 11:41:28.926 | warn | Connection lost
openknx.0 | 2022-08-16 11:41:28.925 | info | [info] 2022-08-16 09:41:28.925 empty internal fsm queue due to inbound_DISCONNECT_REQUEST:
openknx.0 | 2022-08-16 11:41:28.925 | silly | [trace] 2022-08-16 09:41:28.925 (idle): Received DISCONNECT_REQUEST message: {"header_length":6,"protocol_version":16,"service_type":521,"total_length":16,"connstate":{"channel_id":16,"status":0},"hpai":{"header_length":8,"protocol_type":1,"tunnel_endpoint":"192.168.200.17:3671"}}
openknx.0 | 2022-08-16 11:41:28.925 | silly | [debug] 2022-08-16 09:41:28.924 Inbound message: 06100209001010000801c0a8c8110e57
openknx.0 | 2022-08-16 11:41:10.496 | silly | [debug] 2022-08-16 09:41:10.496 (idle): zzzz...
openknx.0 | 2022-08-16 11:41:10.496 | silly | [trace] 2022-08-16 09:41:10.496 (requestingConnState): Received CONNECTIONSTATE_RESPONSE message: {"header_length":6,"protocol_version":16,"service_type":520,"total_length":8,"connstate":{"channel_id":16,"status":0}}
openknx.0 | 2022-08-16 11:41:10.496 | silly | [debug] 2022-08-16 09:41:10.496 Inbound message: 0610020800081000
openknx.0 | 2022-08-16 11:41:10.490 | silly | [trace] 2022-08-16 09:41:10.490 (requestingConnState): UDP sent OK: CONNECTIONSTATE_REQUEST 06100207001010000801000000000000
openknx.0 | 2022-08-16 11:41:10.490 | silly | [trace] 2022-08-16 09:41:10.490 (requestingConnState): Sending CONNECTIONSTATE_REQUEST ==> {"header_length":6,"protocol_version":16,"service_type":519,"total_length":16,"hpai":{"protocol_type":1,"tunnel_endpoint":"0.0.0.0:0"},"connstate":{"channel_id":16,"state":0}}
openknx.0 | 2022-08-16 11:41:10.489 | silly | [trace] 2022-08-16 09:41:10.489 (requestingConnState): Requesting Connection State
openknx.0 | 2022-08-16 11:41:10.489 | silly | [debug] 2022-08-16 09:41:10.489 Requesting Connection State
openknx.0 | 2022-08-16 11:40:10.488 | silly | [debug] 2022-08-16 09:40:10.488 (idle): zzzz...

**Comment by phoeluga** [comment]
I'm facing the same issue using the MDT IP interface.

- Adapter v2.0.7
- ioBroker v4.0.21
- MDT IP Interface SCN-IP000.03

Therefore, I see the above assumption strengthened that these changes can also not be transmitted.

```
2022-11-01 11:38:06.069 - silly: openknx.1 (25491) States user redis pmessage openknx.1.*/openknx.1.Beleuchtung.Beleuchtung_-_Schalten.Beleuchtung_-_Schalten_-_HE03_-_Wohnzimmer_-_Spots-Außen:{"val":true,"ack":false,"ts":1667302686066,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1667298757502}
2022-11-01 11:38:06.072 - debug: openknx.1 (25491) Outbound GroupValue_Write to 3/0/54 val: true from openknx.1.Beleuchtung.Beleuchtung_-_Schalten.Beleuchtung_-_Schalten_-_HE03_-_Wohnzimmer_-_Spots-Außen
2022-11-01 11:38:06.868 - silly: openknx.1 (25491) [debug] 2022-11-01 11:38:06.868 timed out waiting for TUNNELING_ACK
```
After instantiation and during configuration of the adapter, multiple gateways were found after the Detect button was pressed:

![gateway](https://user-images.githubusercontent.com/77971105/199229872-4e29451e-f8b3-4e9e-9677-ed7eafb77636.png)

![gatewayAfterDetection](https://user-images.githubusercontent.com/77971105/199231122-170b8915-c40c-44da-83d8-0e11968df9dc.png)

The logs report the following at this point:

```
2022-11-01 12:05:18.760 - silly: openknx.0 (25922) States system redis pmessage io.messagebox.system.adapter.openknx.0/io.messagebox.system.adapter.openknx.0:{"command":"detectInterface","message":{"ip":"X.X.X.X"},"from":"system.adapter.admin.0","callback":{"message":{"ip":"X.X.X.X"},"id":60,"ack":false,"time":1667304318760},"_id":74479197}
2022-11-01 12:05:18.761 - info: openknx.0 (25922) Detect Interface...
2022-11-01 12:05:19.262 - debug: openknx.0 (25922) sendTo "detectInterface" to system.adapter.admin.0 from system.adapter.openknx.0
```
May this be related?
If more than one is found, maybe the "wrong" one is taken instead?

**Comment by boellner** [comment]
I assume you have more than 2 interfaces in the network for real. If more than one is found then it takes the ip of the faster one. If this is not desired, enter the ip of the correct interface.
Are you using more than one apdater at the same time - where is this line coming from?
2022-11-01 13:31:48.468	silly	[debug] 2022-11-01 12:31:48.468 initializing private connection to Y.Y.Y.Y

**Comment by phoeluga** [comment]
> Are you using more than one apdater at the same time - where is this line coming from?
2022-11-01 13:31:48.468 silly [debug] 2022-11-01 12:31:48.468 initializing private connection to Y.Y.Y.Y

So that's the log output after providing the initial adapter instance configuration (Y.Y.Y.Y is the IP of the KNX IP interface)
I only have one IP interface, so I was wondering why the adapter instance tells me that multiple interfaces were found.

Anyway, I found some time to had a look on this again. I had looked at the readme but didn't think of it again, in my IP interface secure data was activated. After disabling KNX secure (which also implies a hard reset of the IP interface) a connection could be established and the communication between adapter instance and KNX interface is working.

So, as a conclusion for me - and maybe for others facing this problem - RTFM and remember the [Limitations ](https://github.com/iobroker-community-adapters/ioBroker.openknx#limitations )and deactivate KNX secure for now :wink:

@savek-cc Can you check if this might also be the problem for your case?

**Comment by boellner** [comment]
I guess not, since his connection is generally working

**Comment by micha182** [comment]
I am facing similar issues after upgrading the firmware of the device (SCN IP 000.03) to 3.0.6 - at least I have not noticed any issues before.
The connection gets lost every 30 seconds and the log says:

[error] 2022-12-27 23:27:50.647 (idle): Incomplete/unparseable UDP packet: RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds: 061004200014041002002900b060110111020080

Between that disconnects, states are read from the bus and can be sent through the openknx adapter.

**Comment by micha182** [comment]
I was able to try the older fw 3.0.5 again, but no improvement. Before starting the upgrade procedure, everything was running fine - no disconnects or any errors in the log.

However, everytime I do a factory reset on the IP000.03 and leave the device in this state, there are not disconnects visible in the log. Problems begin after setting the physical address and uploading the application to the MDT device.
Can anyone confirm my observation?

**Comment by savek-cc** [comment]
I'm just testing with completely different instance and KNX IP interface - which is in a different subnet.
Is it possible, that we're looking a a NAT issue here?
(ETS has a checkbox for "NAT-connection" and it only works if I enable that)

**Comment by savek-cc** [comment]
The current error is:
[error] 2023-02-11 22:50:18.666 (idle): Incomplete/unparseable UDP packet: TypeError: Cannot read property 'service_type' of undefined at datagramDesc (/opt/iobroker/node_modules/iobroker.openknx/lib/knx/src/Connection.js:328:55) at fsm.FSM.onUdpSocketMessage (/opt/iobroker/node_modules/iobroker.openknx/lib/knx/src/Connection.js:21:19) at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.openknx/lib/knx/src/IpTunnelingConnection.js:32:14) at Socket.emit (events.js:400:28) at Socket.emit (domain.js:475:12) at UDP.onMessage (dgram.js:931:8): 06100420002104020000290a060411e68323800241b4bce01130391b0300802fa6

**Comment by micha182** [comment]
Many of my devices are in different subnets, but that is not an issue in my case. I have not noticed the checkbox you mentioned yet.

In my case, I found that the disconnects were a side effect resulting from a third device, trying to connect to the IP interface. The communication could not be established, so the IP interface forced all clients to disconnect. I think, this behaviour is also described in the protocol.

I found that after going through the specification of the protocol and understanding the structure of the packages.

**Comment by savek-cc** [comment]
[knx_ip.zip](https://github.com/iobroker-community-adapters/ioBroker.openknx/files/10714904/knx_ip.zip)
Attached is a zip file with two captures: One is a connection from an ETS 6 to the IP gateway, the other is a connection from openknx 0.5.2 to the same IP gateway. Both can be opened/analyzed with wireshark. The IP gatway is "192.168.2.31"

**Comment by savek-cc** [comment]
ok  -  apparently it gets disconnected because it's unable to parse the packet; might be/probably related to https://bitbucket.org/ekarak/knx.js/branch/bugfix/issue%2371-sendTunnReq_waitACK

**Comment by savek-cc** [comment]
So - it seems like knx.js is unable to parse packets with "Additional Info" in the ADPU and thus returns an error - which causes the stack to crash and thus not ack the packet which leads to the gateway asking to disconnect after 2 seconds.

**Comment by savek-cc** [comment]
[knx_lib_patch_addinfo.diff.txt](https://github.com/iobroker-community-adapters/ioBroker.openknx/files/10716339/knx_lib_patch_addinfo.diff.txt)
Patch attached to fix this issue (disconnection because packet could not be parsed if it contains more than "0" bytes of additional information).

**Comment by savek-cc** [comment]
Upstream: https://bitbucket.org/ekarak/knx.js/issues/90/invalid-handling-of-addinfo_length-field

**Comment by savek-cc** [comment]
Fixed above issue with https://github.com/iobroker-community-adapters/ioBroker.openknx/pull/338/
Might also work for @micha182 as you also have lines with "serviceType == undefined".
Not sure if this also was the original error though.

**Comment by micha182** [comment]
Thanks, @savek-cc, but in my case, it really was just a side effect.
Nevertheless, happy to read you were able to solve your problem :)
