### ISSUE TITLE
Support 0,1 notation for DPT which expect an object as value

### ISSUE THREAD

**Issue by TA2k** [iobroker-community-adapters/ioBroker.openknx#27]
yes, we should support different notation for all object dpts that are listed in the manual,
but it needs an improvement issue to discuss the options howto implement;

_Originally posted by @boellner in https://github.com/iobroker-community-adapters/ioBroker.openknx/pull/22#discussion_r774026459_

**Comment by boellner** [comment]
I see one problem: complex interfaces are now of type object, and I would not want to remove it.
{"priority":1 bit,"data":1 bit}
How to design the 2nd, alternative interface ?

**Comment by TA2k** [comment]
The only way is to introduce a schema definition for each DPT. But this means to maintain a duplication definition beside knx.js Im not sure if its worth it. 
But at the moment the user receive no information if the the object is malformed. Because the error log from knx.js is not presented to the user

**Comment by boellner** [comment]
can this be closed now with the aboce mentioned issue?
