### ISSUE TITLE
fix review findings - min max

### ISSUE THREAD

**Issue by boellner** [iobroker-community-adapters/ioBroker.openknx#3]
... min/max as number for a boolean state? https://github.com/iobroker-community-adapters/ioBroker.openknx#iobroker-communication-object-description ... but when I read code it would end up this way potentially. Please makse sure to only use min/max with number states tht need it. not for boolean.

**Comment by TA2k** [comment]
https://github.com/iobroker-community-adapters/ioBroker.openknx/pull/8

**Comment by boellner** [comment]
ok
