### ISSUE TITLE
2-level group structure not supported?

### ISSUE THREAD

**Issue by johnssson** [iobroker-community-adapters/ioBroker.openknx#320]
I've imported my 2-level group structure and it was done alright. The sctructure in iobroker was there and as expected, but the actual data/states wasn't functional. no warnings or Errors in the iobroker log, even with loglevel "silly"

Import a structure with 2 level-design

 - Adapter version: v0.3.2
 - JS-Controller version: 4.0.23
 - Node version: v16.18.1
 - Operating system: Debian 5.10.149-2 (2022-10-21) x86_64

Uggly Workaround:
1. Create with ETS a new project with 3-level group structure (not needed to add/configure any of your devices)
2. Import groups (in this step they were converted to 3-level-style)
3. Export groups to XML
4. Import groups in the iobroker openknx adapter (uggly style, because of middle-groups, but the data is there and live)
The same Issue is also in KNX-Ultimate in Node-Red - I have to report it there too...

Issue in 2-level-style:
[iobroker.2022-12-01.2levelstyle.log](https://github.com/iobroker-community-adapters/ioBroker.openknx/files/10134017/iobroker.2022-12-01.2levelstyle.log)
![2022-12-01 16_35_52-objects - iobroker – Mozilla Firefox](https://user-images.githubusercontent.com/49510530/205102046-c8303eef-880a-4bdc-a75a-0761cfc79a27.png)

Functional in converted to 3-level-style:
[iobroker.2022-12-01-3levelstyle.log](https://github.com/iobroker-community-adapters/ioBroker.openknx/files/10134016/iobroker.2022-12-01-3levelstyle.log)

![2022-12-01 16_57_42-objects - iobroker – Mozilla Firefox](https://user-images.githubusercontent.com/49510530/205102037-d05e8d39-3fd9-4a26-b226-7b21903eba5d.png)

**Comment by boellner** [comment]
I think we can implement this with moderate effort.

**Comment by boellner** [comment]
Im adding support for ETS project with 2 level and free group address styles.
