### ISSUE TITLE
No more Local IPv4 network interface after restarting

### ISSUE THREAD

**Issue by fzzybllz** [iobroker-community-adapters/ioBroker.openknx#323]
**Describe the bug**  
I am running iobroker in docker based on the container from ioBroker.docker provided by buanet with bridged network config.
After each restart of iobroker the adapter is unhealthy due to the missing local IPv4 network interface in its config.
The interface itself is not changing and there is only this single option: [IPv4] 172.26.0.3 - eth0

**To Reproduce**  
1. Restart iobroker or the container or docker service or whole system
2. Adapter is unhealthy (orange / not connected to service)
3. Enter adapter config
4. Set local IPv4 network interface
5. Save and close -> Adapter is working

**Expected behavior**  
The network interface keeps set in some way and I do not have to interact after every crash, update or restart.

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: v0.2.5
 - JS-Controller version: 4.0.23
 - Node version: v16.18.1
 - Operating system: Ubuntu 18.04 LTS with docker v20.10.22

**Comment by boellner** [comment]
I was not able to reproduce with adapter version 0.2.5 or latest.
-Could you please also check if persists with latest verion of unstable repo?
-Other settings of the adapter / data of other adapters are not lost?

**Comment by fzzybllz** [comment]
This is/was the only setting that is lost. I upgraded now to 0.5.2 and it seems to be fixed. I will watch it and let you know

**Comment by fzzybllz** [comment]
Nope, did not work unfortunately. Restarting the whole system got me an error: 
_Cannot start KNX Stack Error: Interface 172.26.0.2 not found or has no useful IPv4 address!_

**Comment by fzzybllz** [comment]
Think i fixed it. No issue with your adapter. The IP of my container was changing. By giving the container a static ip it seems to work.
