### ISSUE TITLE
KNX and Jalousie Step

### ISSUE THREAD

**Issue by RenedeRaaf** [iobroker-community-adapters/ioBroker.openknx#329]
Hello,

I have a problem with the KNX adapter and a blind.
Currently I see no possibility to operate a blind with short pressure as a step.
And when I go from up to down I always have to do this 2 times so that it goes completely open or closed.

See [https://forum.iobroker.net/topic/61806/jarvis-jalousie-mit-knx/6](https://forum.iobroker.net/topic/61806/jarvis-jalousie-mit-knx/6) 

Is it possible to add this as a function?

**Comment by boellner** [comment]
In my setup with a MDT actor I have these communication objects which are doing the following:
Langzeitbetrieb auf -> permanently up
Langzeitbetrieb ab -> permanently down
Kurzzeitberieb auf -> if moving in any direction: stop! else  in case of louvre : change angle, in case of shutter: do nothing
Kurzzeitbetrieb ab -> if moving in any direction: stop! else  in case of louvre : change angle, in case of shutter: do nothing

I have a physical button which translates a long press simply into Langzeitbetrieb and a short press into a Kurzzeitbetrieb object up or down.

Lonpress up, (no press), Longpress down leads to this on the KNX bus:
Langzeitbetrieb auf 
Langzeitbetrieb ab

Longpress up, Shortpress up on the button will lead according to first statement to
permanently moving up and then a stop.

I dont use or know Jarvis. To emulate the knx button behavior your visualisation need to distinguish between long press and shortpress and send this to the appropriate iob object / knx ga. KNX adapter is the wrong place for this kind of application logic.

Btw: Im using sliders in my visualisation with 0..100% opening and angle position. I find this more convenient than triggering a command and wait until doing the stop trigger.
