### ISSUE TITLE
"confirmation false received"  every Day... After Restart Adapter it works

### ISSUE THREAD

**Issue by Joogibaer1** [iobroker-community-adapters/ioBroker.openknx#337]
I have a small logic that delivers values ​​from my solar system to the bus.

Everything went well on the first day, the data arrived on the bus. The next morning the log says "confirmation false received" After a restart everything works fine again until the next day it doesn't work anymore. Otherwise the KNX bus runs perfectly. Anyone an idea?
**Expected behavior**  

![image](https://user-images.githubusercontent.com/125185469/218303891-5045cfd1-46d3-47ac-9f7f-997e540ce0c1.png)

 - Adapter version: <0.5.2>
 - JS-Controller version: <6.3.5
 - Node version: <16.19.0
 - Operating system: <os-name>

**Comment by boellner** [comment]
could you paste here the original logfile and maybe a log from ets? thanks
