### ISSUE TITLE
GA button missing. Not possible to import GA. 

### ISSUE THREAD

**Issue by darwas** [iobroker-community-adapters/ioBroker.openknx#339]
**Describe the bug**  

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by darwas** [comment]
<img width="1236" alt="Bildschirm­foto 2023-02-14 um 07 52 16" src="https://user-images.githubusercontent.com/18158910/218661174-a163483e-4621-4eca-b314-8257a28cf54c.png">

**Comment by boellner** [comment]
can be reproduced by setting a small browser window height

**Comment by boellner** [comment]
fix in 0.5.3

**Comment by axelrathey** [comment]
It seems to work here on Firefox. When I zoom in, I get a scrollbar an can scroll down to the "IMPORT ETS XML AND SAVE" button.
