### ISSUE TITLE
Adapter start Autoread Switches dimmer on 

### ISSUE THREAD

**Issue by nstueber** [iobroker-community-adapters/ioBroker.openknx#340]
Hey Community, 

when I start the adapter it does this autoread thing like described in the docu. In my case after this, the dimmable lights are switched on. All other status are untouched (also switchable lights), only dimmable lights are affected. 

I do not have any issues with the official knx adapter ( but I guess it does not do an autoread)

Could this be an adapter thing or a false knx configuration? 

Thank you in advanced

**Comment by boellner** [comment]
You have to find out which object causes this effect and remove this from autoread.
Not all elements are good for readout, eg

Autoread is set to false where it is clear from the DPT that this is a trigger signal. This applies to scene numbers.
