### ISSUE TITLE
Make physical address configurable

### ISSUE THREAD

**Issue by Ralf31337** [iobroker-community-adapters/ioBroker.openknx#347]
OpenKNX is using 0.0.0 as physical address. The other KNX adapters allow me to set 1.0.253. My gateway is a Comexio OS set to 1.0.254. Messages from OpenKNX are seen in ETS debug with 1.0.254 as source, while from KNX adapter it is 1.0.253.

Every state object in Comexio does not update when receiving messages having their origin in OpenKNX/iobroker because Comexio seems to ignore updates with its own address and replaces everything with 0.0.0 by 1.0.254. I admit this seems more to be a bug in Comexio, but in my opinion OpenKNX should be enabled again to allow setting the physical address.

Besides the workaround for Comexio it would improve my debugging with ETS if needed, because you then see which client behind the gateway actually generated a message.

**Expected behavior**  
Possibility/feature to set the physical address. It seemed to be there in the past before version 0.2.5.

**Comment by felsnerino** [comment]
I already opened an issue: https://github.com/iobroker-community-adapters/ioBroker.openknx/issues/257 I guess we only need one for this...
