### ISSUE TITLE
After update from 0.2.5 to 0.5.2 no function anymore

### ISSUE THREAD

**Issue by axelrathey** [iobroker-community-adapters/ioBroker.openknx#348]
**Describe the bug**  
After update from 0.2.5 to 0.5.2 openknx adapter does not work anymore.

**To Reproduce**  
1. Go to 'update from 0.2.5 to 0.5.2'
4. See warning "E_CONNECTION_ID" and "Connection lost"

**Expected behavior**  

**Screenshots & Logfiles**  

**Versions:**  
 - Adapter version: <0.5.2>
 - JS-Controller version: <4.0.24>
 - Node version: <v16.19.0>
 - Operating system: <docker on synology DSM 6.2.4-25556 Update 6>

TCPIP to KNX gateway is ABB IPS/S3.1.1 Firmware 1.0.494

**Additional context**  
After updating from version 0.2.5 to 0.5.2 (0.5.2 became stable from 0.2.5 [without the versions in between] this days) there ist no datatransfer between knx and iobroker anymore. I can't switch lamps etc. from within the ioibroker objects and does not see changing status GA from KNX bus, wenn switching lamps via switch on the wall.
Protokoll will show "E_CONNECTION_ID" and "Connection lost" from openknx instance.

When manuelly returning to 0.25 via github url knx adapter is running as expected.
When manuelly updating from 0.25 to 0.26 via github url I get the same result as with version 0.5.2
So I went down to version 0.2.5 of the OpenKNX adapter

Does anyone has similar problems with the new versions of openknx?

Axel

**Comment by tom2341** [comment]
I have the same problem with the new version.

How do you return back to 0.25 ?

**Comment by axelrathey** [comment]
First on github, may be you need a github login for this, I don't know.
- Go to [ioBroker.openknx](https://github.com/iobroker-community-adapters/ioBroker.openknx) on Github. You will find the github page via ? in the openknx adapter
- Go to releases,
- klick on +35 releases,
- scroll down to 0.2.5 (is on page 2)
- klick on 0.2.5
- scroll down
- copy link address of file Source code (tar.gz) (may be you need the zip-version for iobroker under Windows, i don't know)
- Link would be: https://github.com/iobroker-community-adapters/ioBroker.openknx/archive/refs/tags/v0.2.5.tar.gz
Now in iobroker
- open you iobroker admin, may be you have to login as admin
- go to Adapters,
- switch on expert mode, cat symbol appears, expertmode symbol becomes green color
- click the cat symbol to "install from custom URL"
- choose the rightmost "CUSTOM"
- insert the above link you copied before,
- may be you set "Debug outputs" on, to see more details during install
- click install

After this procedure openknx adapter works for me. Hopefully for you too.

Axel

**Comment by boellner** [comment]
What interface/vendor are you using?

**Comment by boellner** [comment]
could you please add some logfiles?

**Comment by axelrathey** [comment]
Hi,
I tried it today one more time to install openknx 0.5.2 there were no errors during installation of 0.5.2
I switched log level to Info, erased log, then I restarted openknx adapter
After restart I saved the log to TXT an html. I converted html file via Word to docx to add it here.
Below ist the txt log an the docx log. An page 5 there are the warnings with "connection lost" and "E_CONNECTION_ID"
Above to the warnings there is an Info 
"empty internal fsm queue due to inbound_DISCONNECT_REQUEST:"
Why this "DISCONNECT_REQUEST"?

When I use version 0.5.2 of openknx

- I will get the state of my zigbee lamps very slowly. 
- I can't switch on/of my lamps via objects directly in iobroker.

But when I switch lamps via KNX-Switch on the wall the openknx objects were updated.

With version 0.2.5 I did not have this problems

Here the logfiles

[iobroker.2023-03-19.docx](https://github.com/iobroker-community-adapters/ioBroker.openknx/files/11010699/iobroker.2023-03-19.docx)
[iobroker.2023-03-19.log.txt](https://github.com/iobroker-community-adapters/ioBroker.openknx/files/11010701/iobroker.2023-03-19.log.txt)

Thanks for your help 
Axel

**Comment by axelrathey** [comment]
Tried the new 0.5.3 but there are the same problems. Here the log file with debug loglevel.
Axel

[iobroker.2023-03-19a.log.txt](https://github.com/iobroker-community-adapters/ioBroker.openknx/files/11010787/iobroker.2023-03-19a.log.txt)

**Comment by boellner** [comment]
There is a lot of traffic 
-What have you set up for  Minimum send delay between two frames [ms] 
and is it equal to what you measure in ets on startup?

Please try with a higher value

**Comment by axelrathey** [comment]
Hi,

Frames delay [ms] is on 50 ms. I think this is default value, I didn't change it.

Which value do you suggest? 100 ms?

Axel

**Comment by axelrathey** [comment]
where can I measure this delay in ETS Software? I have ETS 6.0.6 installed.
Axel

**Comment by axelrathey** [comment]
After changing frames delay to 100 ms I got into same problems like before.
There are similar log events like in my log last week
Axel

**Comment by boellner** [comment]
Disable first atoread to see if this helps, and if so come down from a high value to a value far enough from the limit.
If it is not helping, post here a ets startup log of your network traffic

**Comment by axelrathey** [comment]
Where can I disable atoread (I think you mean autoread) in openknx? I didn't find neither "atoread" nor "autoread" in openknx config dialog. 
Axel

**Comment by axelrathey** [comment]
OK, after switching off "readout values of autoread iob objects on startup" it seems to work. I now went back to 50 ms frames delay.
I will watch the next days, weather it works.
Axel
