### ISSUE TITLE
Wrong blind status object value in ioBroker, in ETS correct

### ISSUE THREAD

**Issue by gimli1980** [iobroker-community-adapters/ioBroker.openknx#364]
Hi, 

I've the following problem.

I've imported the GAs for status of my blinds from ETS5 to iobroker.
The actors for all blinds are the same from ABB, which has the DPT5.004, so the status goes from 0% - 255%.
The most of my 21 blinds are working fine, status is correct. But I have two blinds, for example my "living room north"-blind where the status just goes from 0% - 100%.

The blinds can be set to a specific value, for example close 200%. That is working fine with every blind. The problem is just the status.

In ETS5, the value of the status GA is fine, but not in iobroker. In ETS is the correct DPT5.004 and the value for closed blind is 255% but in the iobroker-objects it is just 100%. In object-details, the max is set to 100 instead of 255 at the correct working objects and the DPT in iobroker is DPT5.001 and not DPT5.004 like in ETS.

I've imported the whole group adresses in once so I can't understand why the most status are working correctly but the two not.

I've tried to delete the wrong object in iobroker and import the group adresses new, Once with the option "import only GAs that do not exist in IOB objects" and once without but none of the two options fixed the problem.

Situation in ETS5: both GAs working fine, DPT5.004
![rollo ets](https://github.com/iobroker-community-adapters/ioBroker.openknx/assets/120038224/76f27807-6b96-4806-b250-f2321d3bc5fd)

Situation in IOB: The blind Wohnzimmer Nord has the wrong value 100% instead of 255%
![rollo iobroker](https://github.com/iobroker-community-adapters/ioBroker.openknx/assets/120038224/1b3711b7-6520-4c76-b376-7258357f2d5b)

Detail of the wrong object for the blind status, max is automatically set to 100 instead of 255
![rollo objektdetails1](https://github.com/iobroker-community-adapters/ioBroker.openknx/assets/120038224/97771997-156a-48af-83a5-686b3f9b071f)

2nd view of the wrong object, DPT is set to 5.001 instead of 5.004
![rollo objektdetails2](https://github.com/iobroker-community-adapters/ioBroker.openknx/assets/120038224/4f4da7c1-6ce5-4607-8e8c-13c41ba095c1)

Detail of a fine working blind status object "Wohnzimmer West", DPT is set to 5.004 an max is 255
![rollo objektdetails korrekter rollo](https://github.com/iobroker-community-adapters/ioBroker.openknx/assets/120038224/e4a17116-6915-41b7-b41f-4074e318a01a)

**Versions:**  
 - Adapter version: 0.5.2
 - JS-Controller version: 4.0.24
 - Node version: 16.19.1
 - Operating system: Windows

**Comment by boellner** [comment]
It detected dpt 5.004 and 5.003
Can you leave an extract of your ETS export?

**Comment by gimli1980** [comment]
Thanks for you answer. 

The status that are correct in iobroker have 5.004 und the wrong ones 5.001.

It didn't came to my mind to look in the ETS export file, thank for this proposal. 

I checked the file and find out, that the datatype is written wrong in the .xml file by ETS. The blind Wohnzimmer Nord for example has in ETS the correct datatype 5.004 and if if let my show the status in ETS, it is correct 0-255%.

The same status in iobroker is then incorrect 5.001.

So it is a problem in the export of the group adresses from ets und no openknx issue.

Do you have a clue how this could happen?

![Screenshot 2023-09-07 095333](https://github.com/iobroker-community-adapters/ioBroker.openknx/assets/120038224/01e09376-2b2b-4ae9-98c6-5df6af9394aa)

**Comment by boellner** [comment]
No, this I dont know
