### ISSUE TITLE
import-xml-button not there anymore

### ISSUE THREAD

**Issue by baca89** [iobroker-community-adapters/ioBroker.openknx#365]
**Describe the bug**  
I changed some points on my KNX-Installation and would like to update the openknx-adapter with some new groupadresses. I export the XML of the group-Adresses and woult like to import it in the Adapter-Config. But i noticed that the Import-Button is missing.

**To Reproduce**  
1. Go to the Adapter Configuration
2. Theres no Import Button anymore

**Expected behavior**  
that the button is still there.

**Screenshots & Logfiles**  
The the attatched Screenshot 

**Versions:**  
 - Adapter version: v0.5.2
 - JS-Controller version: 4.0.24
 - Node version: v14.21.1
 - Operating system: Debian 5.10.149-2

**Additional context**  
![tempsnip](https://github.com/iobroker-community-adapters/ioBroker.openknx/assets/89659917/a352483a-2321-4dfc-9659-e7ebfbc80c06)

**Comment by TA2k** [comment]
Did you try this on a larger screen? or to zoom out with ctrl -
