### ISSUE TITLE
The connection is lost every minute with status 33 and reconnected successfully

### ISSUE THREAD

**Issue by hebrit** [iobroker-community-adapters/ioBroker.openknx#372]
**Describe the bug**  
The connection is not working properly.
Although a successful connection is established, it is disconnected and re-established every minute. However, no values are assigned to the objects.

**To Reproduce**  
All objects have the value "null".
Below the logs it shows that the connection is reestablished every minute after being disconnected with status 33.

**Expected behavior**  
A stable connection with current values ​​at the objects.

**Screenshots & Logfiles**  
<html>
<body>

openknx.0 | 1263 | 2023-06-06 21:52:11.779 | silly | [debug] 2023-06-06 19:52:11.779 (sendTunnReq_waitACK): >>>>>>> successfully sent seqnum: 0
-- | -- | -- | -- | --
openknx.0 | 1263 | 2023-06-06 21:52:11.778 | silly | [trace] 2023-06-06 19:52:11.778 (sendTunnReq_waitACK): UDP sent OK: TUNNELING_REQUEST_L_Data.req 061004200015040000001100bce00000450c010000
openknx.0 | 1263 | 2023-06-06 21:52:11.778 | silly | [trace] 2023-06-06 19:52:11.777 (sendTunnReq_waitACK): Sending TUNNELING_REQUEST_L_Data.req ==> {"header_length":6,"protocol_version":16,"service_type":1056,"total_length":21,"hpai":{"protocol_type":1,"tunnel_endpoint":"0.0.0.0:0"},"tunn":{"protocol_type":1,"tunnel_endpoint":"0.0.0.0:0"},"tunnstate":{"channel_id":0,"tunnel_endpoint":"192.168.0.15:3671","seqnum":0},"cemi":{"msgcode":17,"ctrl":{"frameType":1,"reserved":0,"repeat":1,"broadcast":1,"priority":3,"acknowledge":0,"confirm":0,"destAddrType":1,"hopCount":6,"extendedFrame":0},"src_addr":"0.0.0","dest_addr":"8/5/12","apdu":{"apci":"GroupValue_Read","tpci":0,"data":0}},"disenqueue":true}
openknx.0 | 1263 | 2023-06-06 21:52:11.773 | silly | [debug] 2023-06-06 19:52:11.773 timed out waiting for TUNNELING_ACK - retry
openknx.0 | 1263 | 2023-06-06 21:52:10.772 | silly | [debug] 2023-06-06 19:52:10.772 (sendTunnReq_waitACK): >>>>>>> successfully sent seqnum: 0
openknx.0 | 1263 | 2023-06-06 21:52:10.772 | silly | [trace] 2023-06-06 19:52:10.772 (sendTunnReq_waitACK): UDP sent OK: TUNNELING_REQUEST_L_Data.req 061004200015040000001100bce00000450c010000
openknx.0 | 1263 | 2023-06-06 21:52:10.771 | silly | [trace] 2023-06-06 19:52:10.771 (sendTunnReq_waitACK): Sending TUNNELING_REQUEST_L_Data.req ==> {"header_length":6,"protocol_version":16,"service_type":1056,"total_length":21,"hpai":{"protocol_type":1,"tunnel_endpoint":"0.0.0.0:0"},"tunn":{"protocol_type":1,"tunnel_endpoint":"0.0.0.0:0"},"tunnstate":{"channel_id":0,"tunnel_endpoint":"192.168.0.15:3671","seqnum":0},"cemi":{"msgcode":17,"ctrl":{"frameType":1,"reserved":0,"repeat":1,"broadcast":1,"priority":3,"acknowledge":0,"confirm":0,"destAddrType":1,"hopCount":6,"extendedFrame":0},"src_addr":"0.0.0","dest_addr":"8/5/12","apdu":{"apci":"GroupValue_Read","tpci":0,"data":0}},"disenqueue":true}
openknx.0 | 1263 | 2023-06-06 21:52:10.767 | silly | [debug] 2023-06-06 19:52:10.766 timed out waiting for TUNNELING_ACK - retry
openknx.0 | 1263 | 2023-06-06 21:52:09.780 | silly | States user redis pmessage openknx.0.*/openknx.0.info.connection:{"val":true,"ack":true,"ts":1686081129777,"q":0,"from":"system.adapter.openknx.0","user":"system.user.admin","lc":1686075789885}
openknx.0 | 1263 | 2023-06-06 21:52:09.778 | silly | States user redis pmessage openknx.0.*/openknx.0.info.connection:{"val":false,"ack":true,"ts":1686081129776,"q":0,"from":"system.adapter.openknx.0","user":"system.user.admin","lc":1686081129776}
openknx.0 | 1263 | 2023-06-06 21:52:09.765 | silly | [debug] 2023-06-06 19:52:09.765 (sendDatagram): >>>>>>> successfully sent seqnum: 0
openknx.0 | 1263 | 2023-06-06 21:52:09.765 | silly | [trace] 2023-06-06 19:52:09.765 (sendDatagram): UDP sent OK: TUNNELING_REQUEST_L_Data.req 061004200015040000001100bce00000450c010000
openknx.0 | 1263 | 2023-06-06 21:52:09.764 | info | Connected!
openknx.0 | 1263 | 2023-06-06 21:52:09.716 | silly | [trace] 2023-06-06 19:52:09.716 (sendDatagram): Sending TUNNELING_REQUEST_L_Data.req ==> {"header_length":6,"protocol_version":16,"service_type":1056,"total_length":21,"hpai":{"protocol_type":1,"tunnel_endpoint":"0.0.0.0:0"},"tunn":{"protocol_type":1,"tunnel_endpoint":"0.0.0.0:0"},"tunnstate":{"channel_id":0,"tunnel_endpoint":"192.168.0.15:3671","seqnum":0},"cemi":{"msgcode":17,"ctrl":{"frameType":1,"reserved":0,"repeat":1,"broadcast":1,"priority":3,"acknowledge":0,"confirm":0,"destAddrType":1,"hopCount":6,"extendedFrame":0},"src_addr":"0.0.0","dest_addr":"8/5/12","apdu":{"apci":"GroupValue_Read","tpci":0,"data":0}},"disenqueue":true}
openknx.0 | 1263 | 2023-06-06 21:52:09.708 | silly | [debug] 2023-06-06 19:52:09.708 (idle): zzzz...
openknx.0 | 1263 | 2023-06-06 21:52:09.707 | silly | [debug] 2023-06-06 19:52:09.707 --- Connected in TUNNELING mode ---
openknx.0 | 1263 | 2023-06-06 21:52:09.707 | silly | [debug] 2023-06-06 19:52:09.707 Got connection state response, connstate: E_CONNECTION_ID, channel ID: 0
openknx.0 | 1263 | 2023-06-06 21:52:09.706 | silly | [trace] 2023-06-06 19:52:09.706 (connecting): Received CONNECTIONSTATE_RESPONSE message: {"header_length":6,"protocol_version":16,"service_type":520,"total_length":8,"connstate":{"channel_id":0,"status":33}}
openknx.0 | 1263 | 2023-06-06 21:52:09.705 | silly | [debug] 2023-06-06 19:52:09.705 Inbound message: 0610020800080021
openknx.0 | 1263 | 2023-06-06 21:52:09.705 | silly | [trace] 2023-06-06 19:52:09.704 (connecting): UDP sent OK: CONNECTIONSTATE_REQUEST 06100207001000000801000000000000
openknx.0 | 1263 | 2023-06-06 21:52:09.703 | silly | [trace] 2023-06-06 19:52:09.703 (connecting): Sending CONNECTIONSTATE_REQUEST ==> {"header_length":6,"protocol_version":16,"service_type":519,"total_length":16,"hpai":{"protocol_type":1,"tunnel_endpoint":"0.0.0.0:0"},"connstate":{"channel_id":0,"state":0}}
openknx.0 | 1263 | 2023-06-06 21:52:09.699 | silly | [debug] 2023-06-06 19:52:09.699 got connect response
openknx.0 | 1263 | 2023-06-06 21:52:09.699 | silly | [trace] 2023-06-06 19:52:09.698 (connecting): Received CONNECT_RESPONSE message: {"header_length":6,"protocol_version":16,"service_type":518,"total_length":8,"connstate":{"channel_id":0,"status":34}}
openknx.0 | 1263 | 2023-06-06 21:52:09.698 | silly | [debug] 2023-06-06 19:52:09.698 Inbound message: 0610020600080022
openknx.0 | 1263 | 2023-06-06 21:52:09.695 | silly | [trace] 2023-06-06 19:52:09.694 (connecting): UDP sent OK: CONNECT_REQUEST 06100205001a0801000000000000080100000000000004040200
openknx.0 | 1263 | 2023-06-06 21:52:09.694 | warn | E_CONNECTION_ID
openknx.0 | 1263 | 2023-06-06 21:52:09.693 | silly | [trace] 2023-06-06 19:52:09.692 (connecting): Sending CONNECT_REQUEST ==> {"header_length":6,"protocol_version":16,"service_type":517,"total_length":26,"hpai":{"protocol_type":1,"tunnel_endpoint":"0.0.0.0:0"},"tunn":{"protocol_type":1,"tunnel_endpoint":"0.0.0.0:0"},"cri":{"connection_type":4,"knx_layer":2,"unused":0},"connstate":{"state":0}}
openknx.0 | 1263 | 2023-06-06 21:52:09.687 | silly | [debug] 2023-06-06 19:52:09.687 Connecting via 192.168.0.12...
openknx.0 | 1263 | 2023-06-06 21:52:09.687 | silly | [debug] 2023-06-06 19:52:09.687 useTunneling=true
openknx.0 | 1263 | 2023-06-06 21:52:09.686 | warn | Connection lost

</body>
</html>

**Versions:**  
 - Adapter version: 0.5.2
 - JS-Controller version: 4.0.23
 - Node version: v16.19.0
 - Operating system: Linux raspberrypi 5.15.84-v7l
 - Hardware: Raspberry Pi 4 Model B Rev 1.5

**Additional context**

**Comment by boellner** [comment]
-What type of KNX Interface, vendor... do you use?
-Please do some bus load measurement and if number correlates with disconnect, increase the delay time between consecutive frames

**Comment by boellner** [comment]
cannot reproduce
