### ISSUE TITLE
Moved from KNX Adapter to OpenKNX and unable to import from ETS 6.0.6

### ISSUE THREAD

**Issue by AJ150916** [iobroker-community-adapters/ioBroker.openknx#398]
**Describe the bug**  
Today I've switched from ioBroker KNX Adapter to the OpenKNX Adapter and everything went OK and OpenKNX is up and running.
However I'm unable to import the exported XML for the GAs.

**To Reproduce**  
Every time I try to import the XML file, even after a reboot of the Raspberry

**Expected behavior**  
For example one line, all other entries have the same issue:

Imported 0 states successfully
Not adding Bewegung.Neue_Mittelgruppe.Flur_Foyer because no DPT is assigned to 0/0/1. The GA is not connected to a KO in ETS

**Screenshots & Logfiles**  

openknx.0 | 2023-09-15 20:27:19.926 | info | /opt/iobroker/node_modules/iobroker.js-controller
-- | -- | -- | --
openknx.0 | 2023-09-15 20:27:19.925 | info | Connecting to knx gateway: 192.168.x.xx:3671 minimum send delay: 50ms debug level: info
openknx.0 | 2023-09-15 20:27:19.882 | info | starting. Version 0.5.3 in /opt/iobroker/node_modules/iobroker.openknx, node: v16.19.1, js-controller: 5.0.12

**Versions:**  
 - Adapter version: v0.5.3
 - JS-Controller version: 5.0.12
 - Node version: v16.19.1
 - Operating system: Rasberry Pi Bullseye

**Comment by boellner** [comment]
You have an invalid configuration, please make sure that dpt is fully set in ETS
If you think your config is correct anyway, please post (an extract) of your xml file
