### ISSUE TITLE
feature: generate more log messages (enable/disable)

### ISSUE THREAD

**Issue by mhuber77** [iobroker-community-adapters/ioBroker.openknx#456]
Since the last update, I believe with the "generate more log messages" feature. my log is full with lots of messages like "warn Ignoring GroupValue_Write of of unknown GA 1/4/71". The GA doesn't exist in my IOBroker installation.

It would be good if you could turn these log messages on or off in the adapter settings.

**Comment by hebrit** [comment]
I've the same issue, but the GA is available under iobroker Objects.
![Screenshot 2024-03-03 101505](https://github.com/iobroker-community-adapters/ioBroker.openknx/assets/93495050/6c4e220f-2039-46ae-ab74-bc834d0c3d36)

**Comment by mhuber77** [comment]
> I made it configurable, please try out v0.7.3-alpha.1

ok thanks! It works :-)
