### ISSUE TITLE
inform user about DPT without subtype while importing

### ISSUE THREAD

**Issue by TA2k** [iobroker-community-adapters/ioBroker.openknx#47]
Should we inform the user about imported GA with DPT without subtype?
Like DPT-5 because the user is wondering about missing units because it false selected in ETS

**Comment by boellner** [comment]
Its not possible to find out if user set 5 on purpuse or it was set by ets by mistake. So better not give possibly false warnings, better write a chapter in the manual

**Comment by TA2k** [comment]
It only to give a information and a hint to the manual otherwise he is not aware why the subtype was not imported

**Comment by Videonisse** [comment]
I'm also positive to inform the user of eventual errors in their Group Address structure. Maybe it doesn't have to be written to the log but could at least be viewed in the Adapter GUI after import. Could perhaps also be possible to select "Ignore error message next time"?

**Comment by boellner** [comment]
Problem is more complex, if user sets different subtypes then ets exports the one with the lowest number. We have no chance to detect this on import side

**Comment by TA2k** [comment]
But we have the possibility to inform him and he can double check. But without any information is hard for the user

**Comment by boellner** [comment]
can be closed
