### ISSUE TITLE
Possible to import single GAs? And GAs that are not linked to any KO?

### ISSUE THREAD

**Issue by memberxx** [iobroker-community-adapters/ioBroker.openknx#480]
Hi, currently using the XML export from ETS the KNX instance does not import Group addresses that are not linked to any KNX KO

E.g. I use some GAs that are just updated by a server, so not linked to any KO. Those are exported but not imported by KNX Adapter.

Also would be great if I could easily add one single new GA instead of exporting all again, importing...?

Thx

**Comment by boellner** [comment]
If it is not linked, why is it existing?

You can import xml again an disable overwriting,
or modify the import file by hand

**Comment by memberxx** [comment]
> If it is not linked, why is it existing? Please check the log to understand what mandatory information is missing for the importer.
> 

only a server, no KO, is sending to some GAs and only server or Home Assistant or IOBroker are reading it. That’s why there is no linked KO. E. G. Used for some scenes

**Comment by boellner** [comment]
Please check the log, there is mandatory information missing for the importer to work
