### ISSUE TITLE
warning Ignoring GroupValue_Read of unknown GA

### ISSUE THREAD

**Issue by axelrathey** [iobroker-community-adapters/ioBroker.openknx#496]
Hi,

I get a warning in iobroker protokoll like this

"Ignoring GroupValue_Read of unknown GA 15/7/132"

and some more other KNX GAs
But there ist no GA 15/7/132 and the other GAs also do not exists either in openknx neither in the ETS or the KNX Komponents. GA 15/7/131 and GA 15/7/133 exists.

What ist the problem. Where can I check from which system this GroupValue_Read comes?

Thanks a lot. Axel

**Comment by boellner** [comment]
What is in the ETS log?

**Comment by boellner** [comment]
no response
