### ISSUE TITLE
support of KNX secure

### ISSUE THREAD

**Issue by boellner** [iobroker-community-adapters/ioBroker.openknx#59]
discussed in other projects
lets see how we can introduce it

https://github.com/openhab/openhab-addons/issues/8872
https://github.com/Supergiovane/node-red-contrib-knx-ultimate

**Comment by Supergiovane** [comment]
Hi Boellner
KNX Secure is very hard to implement. It involves a lot of knowledge in crypto and, other than that, the documentation also involves a lot of study.
Personally, i've succesfully decrypted the ETS Keyring file with the provided password and i'm working on the first KNX Secure handshake between KNX-Ultimate and a KNX-IP Secure Interface in TCP mode.
But such stuffs are sooooooo time consuming!

**Comment by boellner** [comment]
Hi @Supergiovane 
thanks for your insights. What is your strategy, are you planning to port the KNX secure feature back to the knx.js library or is your work now a complete fork? I have seen you did a lot of other improvements in before.
Are both libraries fully interoperable?

**Comment by Supergiovane** [comment]
Hi
I’ve developed my own code partially based on heavy modified knx.js, to get rid of the “machina” framework and to better adhere to the knx ISO standard. 
No, knx.js and knx-umtimate API are now two totally different things, but adapting the crypto code is not an issue. 
For example, the code for validatind and decrypting the ETS keyring file can be used also for sure in iobroker with a little effort.

**Comment by boellner** [comment]
Ok I'll wait for your work to complete and then check how to proceed, meanwhile we're correcting bugs in the knx lib that might be also be in your product and knx lib is also fixing things, adding dpts etc. Not sure how to keep those things in sync

**Comment by Supergiovane** [comment]
Hi
No, thanks. I’ve already fixed and improved many things. I’m not using knx.js. Thank you anyway. Have a good 2022

**Comment by boellner** [comment]
Im not going to integrate knx ultimate library. Risk is too high.
