### ISSUE TITLE
fix review finding - push

### ISSUE THREAD

**Issue by boellner** [iobroker-community-adapters/ioBroker.openknx#6]
https://github.com/iobroker-community-adapters/ioBroker.openknx/blob/c383547de3a3bc84cd3e87ef3153e880090c6ce2/io-package.json#L65
https://github.com/iobroker-community-adapters/ioBroker.openknx/blob/c383547de3a3bc84cd3e87ef3153e880090c6ce2/main.js#L351
shouldn't it be push?

https://github.com/ioBroker/ioBroker.repositories/pull/1553

**Comment by TA2k** [comment]
fixed 
https://github.com/iobroker-community-adapters/ioBroker.openknx/commit/969c8b09c85d608da21ebd5992775dd73ebae24f
