### ISSUE TITLE
XML für Test der Status GA

### ISSUE THREAD

**Issue by mane444** [iobroker-community-adapters/ioBroker.openknx#60]
Hier eine Datei zum Testen.
[knx_xml.zip](https://github.com/iobroker-community-adapters/ioBroker.openknx/files/7789493/knx_xml.zip)

**Comment by boellner** [comment]
Ich komme jetzt auf auf 75 matches

Deine Benamung ist oft nicht eindeutig.

OG Schlafen Rollo 1 Position Sollwert Status
OG Schlafen Rollo 1 Sollwert

Reserve Rollo Sollwert Lamellenpos
Reserve Rollo Lamellenposition Sollwert  Status

Reserve Rollo Status
??

**Comment by mane444** [comment]
Hi, kurze Rückmeldung:
Nach einer Nachbearbeitung der GA hab ich das ganze nochmal mit der v0.1.12 gemacht. Mit einer Einstellung der Mindestähnlichkeit auf 0,8 schafft der Adapter alle GA (114) außer der 3 Gartensteckdosen die nur durch eine Nummer zu unterscheiden sind.
Das ist aber sicher mit einer besseren Benamung der GA bestimmt auch noch machbar.

**Comment by boellner** [comment]
mit 0.1.12 kommt ein update vom algorithmus, damit sollte es noch besser sein

**Comment by mane444** [comment]
Ich hab das gleich nochmal getestet. Ich finde dat Tool super.
- alle eindeutigen GA wurden zugeordnet. Bei den nicht eindeutigen GA kann man ja immer noch händisch im Alias nacharbeiten was ich sehr gut finde. 
- Die Einheiten wurden übernommen.

Ganz große Lob von meiner Seite für den gelungenen Adapter.
