### ISSUE TITLE
Alias generation fails with dimmers

### ISSUE THREAD

**Issue by peteruhrig** [iobroker-community-adapters/ioBroker.openknx#74]
My KNX project follows the "EIBMeier Kurs" system, which is not uncommon in the German-speaking world, which means that the main group 1 is for Lights and switching sockets, the middle group tells us what type we have:

1: Schalten (Ein/Aus 1 Bit) - Neuanlage immer hier! -
2: Dimmen (+/- 4 Bit) - Kopieren! -
3: Wert (Dimmer 1 Byte) - Kopieren! -
4: Rückmeldung schalten (Ein/Aus 1 Bit) - Kopieren! -
5: Rückmeldung Wert (Dimmer 1 Byte) - Kopieren! -

Every address in my project is then named accordingly:
1/1/21: DG Arbeitszimmer Licht s
1/4/21: DG Arbeitszimmer Licht RMs
With the regular expression "RM." and a similarity of 0.8, this works fine and an alias is created for every on/off switch.

However, with dimmers, all 5 types of addresses are connected and accordingly imported:
1/1/40: DG Kinderzimmer 1 Licht s
1/2/40: DG Kinderzimmer 1 Licht d
1/3/40: DG Kinderzimmer 1 Licht w
1/4/40: DG Kinderzimmer 1 Licht RMs
1/5/40: DG Kinderzimmer 1 Licht RMw

What I would expect in an ideal world is two pairs of aliases:
1/1/40 with 1/4/40
and
1/3/40 with 1/5/40

However, the aliasing algorithm creates only one pair that does not fit together:
```
    "alias": {
      "id": {
        "read": "openknx.0.Beleuchtung_&_schaltbare_Steckdosen.Rückmeldung_schalten_(Ein_Aus_1_Bit)_-_Kopieren!_-.DG_Kinderzimmer_1_Licht_RMs",
        "write": "openknx.0.Beleuchtung_&_schaltbare_Steckdosen.Wert_(Dimmer_1_Byte)_-_Kopieren!_-.DG_Kinderzimmer_1_Licht_w"
      }
    }
```
Given the different DPT values, these should not have been paired together at all. I'm wondering whether a check of DPT compatibility may fix this problem.

Edit: The version used was installed today from the "beta" repository. The interface says it is version 0.1.13. Is this the version I'm supposed to be using?

**Comment by TA2k** [comment]
Please try stat(e|us)|rm|rm.|rückmeldung|\\svalue

**Comment by peteruhrig** [comment]
Tried it out. It works just the same as my "RM." for my project, so I think it would be an improvement to use that as a default for a future release. However, would make it more specific so as to not capture whitespace:
stat(e|us)|rm(s|w)?|rückmeldung|\svalue
or maybe
stat(e|us)|rm\w?|rückmeldung|\svalue

But the problem of the alias combining two elements with incompatible datapoints remains. If you would like to verify the problem, you can test it with my XML file, which you can temporarily find here: http://go.peter-uhrig.de/gruppenadressen_export.xml
The problematic cases are 1/[1-5]/(40|41|43|44).

**Comment by TA2k** [comment]
I tested it is has a better matching with rm|rm. because not everyone has character or using character s/w. I would start with a more general regex. I will test the xml

**Comment by TA2k** [comment]
Can you please try stat(e|us)|rm|rm.|rückmeldung|\svalue with 0.9 ?

**Comment by peteruhrig** [comment]
Thank you! It works like a charm. And it also works like a charm with 0.8. And it also works like a charm with "RM." and 0.8.

I love it, but I'm so confused! I delete all aliases and the entire openknx tree before every import. And still, it seems as if the system has learned something and now gets it right every time. How is this possible?

**Comment by TA2k** [comment]
I have no idea

**Comment by boellner** [comment]
DPT mismacht gives you a warning in the log. But it does not neccesarily mean it is wrong, the write can be 1.001 and the status 1.011

**Comment by boellner** [comment]
did you play with the "group range" checkbox? Selecting it makes the matching algo consider your main and middle group , which is not matching well.
It also takes a adapter reset that the selection gets active. Maybe that is the confusion

**Comment by peteruhrig** [comment]
I did switch it on and off yesterday, but I think it was off for every import today. But you are right, maybe it was still not restarted and did weird things because of that. At any rate, I'm very happy with the way it is working now. Thanks to both of you!!
