### ISSUE TITLE
Generated aliases missing required "native" attribute

### ISSUE THREAD

**Issue by peteruhrig** [iobroker-community-adapters/ioBroker.openknx#75]
The aliases generated by openknx do not have the "native" attribute, i.e. I have to manually add
```
,
native: {}
```
at the end of the object.

This is a problem that other people have noticed before for other adapters, see the discussion here: 
https://forum.iobroker.net/post/342120
(Start at the highlighted post and read the next 15 or 20 comments, if you like.)
The most important quote is this: "Sagen wir es so: Ein State-Objekt ohne "native" ist an sich ungültig, auch wenn native leer ist."

I thus suggest we simply add the empty property to every alias created.

Version used is 0.1.13 installed from the beta repository on 2 January 2022.

**Comment by TA2k** [comment]
Fix in github version and with next release
