### ISSUE TITLE
Add feature to extract room from GA name

### ISSUE THREAD

**Issue by TA2k** [iobroker-community-adapters/ioBroker.openknx#77]
iobroker working with rooms normally this can extracted from the GA name

**Comment by TA2k** [comment]
@boellner Are we allowed to add this feature? Or you don't want it?

**Comment by boellner** [comment]
im not sure, 
how would you do this , e.g. by a widely used naming convention?
A device is bound to a room, a ga is connecting devices which are not neccessarily in the same room.

**Comment by TA2k** [comment]
Normally the room is encoded in the GA name. You can define a regex to extract the room. You can also enter a GA ranges to exclude Groups from extraction.

**Comment by boellner** [comment]
im going to reject enhancement in a few days, does not to be a common use case to add always room names to ga's
and it is difficult to find a good regexp

**Comment by TA2k** [comment]
It is official recommend to add room in the GA.
regex is simple 
please add this feature

**Comment by boellner** [comment]
Where can I see this official recommendation?

**Comment by TA2k** [comment]
You really name your GAs without a room reference?

https://www.knx.org/wAssets/docs/downloads/Marketing/Flyers/KNX-Project-Preparation/KNX-Project-Preparation_de.pdf
https://support.knx.org/hc/en-us/articles/360007432720-Project-Wizard
https://www.bemi.fi/knx-group-address-best-practices-and-guidelines/
https://smarthomebau.de/knx-ets-gruppenadressen-die-geordnete-struktur-im-einfamilienhaus/

**Comment by boellner** [comment]
No, I'm doing it.
All your examples are already very different. It need a lot of user interaction to come to an acceptable result.
Please provide a proposal how this is done (gui, time of import, reoccuring..) and what to do with the data

**Comment by TA2k** [comment]
After import inform the user to create aliases and room detection.
Provide a default regex where the first group is matching the room.
After pressing a Button sse this room information to write it in the ioBroker states.
Room and Function information are needed to create Vis automatically

**Comment by boellner** [comment]
closing this feature request because of low contribution and no interest
