### ISSUE TITLE
Alias creation dialog not properly usable on "smaller" screen

### ISSUE THREAD

**Issue by peteruhrig** [iobroker-community-adapters/ioBroker.openknx#78]
Windows 10, Browser Google Chrome, Resolution 1920*1080, 125% zoom in control panel settings, 100% zoom in Chrome.

I cannot reach any of the textboxes with my mouse, only via the TAB key on the keyboard. The reason is that the &lt;div&gt; for the input field of the checkbox sits on top of those textboxes. This also leads to the weird overlap of the checkbox with the button.

Screenshot:
![image](https://user-images.githubusercontent.com/19432934/147935034-6e127268-16ea-4ad7-8efd-966bfa50867b.png)

With DevTools enabled:
![image](https://user-images.githubusercontent.com/19432934/147935611-5b9e67b5-b44e-411d-93c4-18230d7ada1d.png)

By contrast, everything works perfectly on my 4k screen.

**Comment by boellner** [comment]
I tested with firefox, and the checkbox overflow to one line is above the button.
Not sure if brower has an influence or if was some cleanup meanwhile, lets recheck on the next releae

**Comment by boellner** [comment]
please recheck with 0.1.14 in the next days when it is out

**Comment by peteruhrig** [comment]
The problem does not occur in 0.1.14 any more. Thanks a lot!
