### ISSUE TITLE
How to set comment to 'GroupValue_Read'

### ISSUE THREAD

**Issue by FMode** [iobroker-community-adapters/ioBroker.openknx#87]
How to set comment to  'GroupValue_Read' in a iobroker script?

What I can see from the logs and source of main.js "c" seems to be removed so it sends a 4711 as GroupvalueWrite.

```
var schedule1;

schedule1 = schedule('*/15 * * * * *', async function () {
  setState('openknx.0.Heizungsystem_Rotex_Zennio_Interface.Energie_Verbrauch_Total', {val: 4711, ack: false, c: 'GroupValue_Read'});
});

```
Thank you

**Comment by boellner** [comment]
I can confirm this behaviour, the script is overwriting the comment. I have to change the interface...

**Comment by boellner** [comment]
problem is this line of code in sandbox.js
```
        // set as comment: from which script this state was set.
        if (!isBinary) {
            state.c = sandbox.name;
        }
```
I am adding null value write as interface to trigger group value read

**Comment by boellner** [comment]
it is part of master branch @FMode 
please test it
will be part of 0.1.15 release then

**Comment by FMode** [comment]
sending string with "null" works with fbf5f691847726aa346f8cdffa9d20c3c6dd4ceb -> triggers Read

**Comment by boellner** [comment]
problem is, it is against the specs. I'm using now the q (quality) element with value 0x10. Please check if this is fine

**Comment by FMode** [comment]
0x10 also works

**Comment by boellner** [comment]
thanks for confirmation, I release the next version and announce it
