### ISSUE TITLE
Please add iobroker sentry plugin

### ISSUE THREAD

**Issue by TA2k** [iobroker-community-adapters/ioBroker.openknx#96]
Please add iobroker sentry plugin

**Comment by boellner** [comment]
please add a description of the advantages and how to make use of it

**Comment by TA2k** [comment]
https://docs.sentry.io/platforms/javascript/

Sentry's SDKs enable automatic reporting of errors and exceptions.

**Comment by boellner** [comment]
that is clear; i meant how is it commonly used and integrated into iob adapters ?

**Comment by Apollon77** [comment]
see https://github.com/ioBroker/plugin-sentry

**Comment by boellner** [comment]
I see it had been requested already without proper communication to the project.
@Apollon77 please add boellnerboellner@gmail.com to the IOB sentry server
meanwhile Ill use the free service.

**Comment by Apollon77** [comment]
@boellner Yes @TA2k request it already back in december and I provided him all details ... you get an invite. Please register ad directly activate 2FA and store the 2FA recovery keys

**Comment by Apollon77** [comment]
The DSN is https://f87a314b36ef451aa291655ae13e2831@sentry.iobroker.net/165

**Comment by boellner** [comment]
working, thanks
will be added to 0.1.16, please check and close then
