### ISSUE TITLE
Please provide stable version

### ISSUE THREAD

**Issue by TA2k** [iobroker-community-adapters/ioBroker.openknx#98]

**Comment by boellner** [comment]
after discovery is accepted ...

**Comment by TA2k** [comment]
Can you explain why is necessary to wait? The stable version can work without discovery feature.

**Comment by Apollon77** [comment]
it is also "Other way around" ... Adapter should be in stable to make sure we not have it in discovery stable but adapter is not  :-) So yes, better do stable addition anytime before

**Comment by boellner** [comment]
Because it is required here: https://github.com/ioBroker/ioBroker.repositories/#samples
Discovery checks for availability, so no conflict with this sequence. Or do is miss something?

**Comment by Apollon77** [comment]
I adjusted the relevant section to be correct.

**Comment by boellner** [comment]
https://github.com/ioBroker/ioBroker.repositories/pull/1616

**Comment by boellner** [comment]
done 0.1.15
