### ISSUE TITLE
Please add alternative to aliases

### ISSUE THREAD

**Issue by TA2k** [iobroker-community-adapters/ioBroker.openknx#99]
I don't want use aliases please provide an alternative like the knx adapter.

**Comment by boellner** [comment]
it has been discussed now many times. There is no argument given why we should have a copy of the knx adapter. Closed

**Comment by TA2k** [comment]
Ok again you alone decide which features are allowed to implement and which not and not discussion are allowed.

**Comment by boellner** [comment]
I decide in what direction this project goes. And I ensure that nobody adds stuff without properly communication. Anarchy is not leading to a good product. 
Everybody may propose new features with the new formal template and if there are arguments to do it  and it is not jeopardizing the overall concept it is open for realization

**Comment by TA2k** [comment]
Ok then you should think about it to remove it from the community adapter organisation to allow a real community leaded adapter where everyone can contribute.
Normally this adapters are not directed by one person which decides what good or bad arguments or decides which discussion are allowed or not.
